# Generated by Django 4.2 on 2023-05-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
