# Generated by Django 4.2 on 2023-05-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='seller',
            new_name='publisher',
        ),
    ]
