# Generated by Django 4.2 on 2023-05-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_products_prod_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
