# Generated by Django 4.2 on 2023-05-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_seller_products_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='descp',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='products',
            name='descp',
            field=models.CharField(max_length=400),
        ),
    ]
