# Generated by Django 4.2 on 2023-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
